### ISSUE TITLE
Leading plus

### ISSUE THREAD

**Issue by schneck** [akrumel/react-editmask#1]
Hi there,

I'd like to place a leading plus as a literal - how'd that work?

Thanks!

**Comment by akrumel** [comment]
Away from my computer today and will post a response tomorrow morning (MST).

**Comment by akrumel** [comment]
Escaped pattern operators were not being handled property. Use latest 4.0.2 for fix.

**Comment by akrumel** [comment]
To answer your question, the mask '/+d' would output '+1' for the inputs '1' and '+1'.

**Comment by schneck** [comment]
Hi,

thanks for the changes, there is one thing that does not work properly though: I'm using the following pattern to enter international phone numbers: `/+dd?d? d* d*`.
It accepts multiple pluses at the beginning, however, which should not be the case.

Anything I'm doing wrong here?

Thanks!

**Comment by akrumel** [comment]
Should be working. Added a test to check for multiple '+' at beginning with patter `/+d` and created a ui example. Would you mind checking your version with `npm list react-editmask` and make sure its 4.0.3. 4.0.2 should work as well.

**Comment by oertels** [comment]
Thanks for the update, it works now - and yes, should've been also working with 4.0.2, maybe I made some mistake. Thanks anyway, it's a really helpful tool.
